apiVersion: apps/v1
kind: Deployment
metadata:
    name: openreplay
    labels:
        app: openreplay
spec:
    replicas: 1
    selector:
        matchLabels:
            app: openreplay
    template:
        metadata:
            labels:
                app: openreplay
        spec:
            containers:
            - name: openreplay
              imagePullPolicy: Always
              image: k3d-registry.localhost:5000/openreplay:local
              resources:
                limits:
                  memory: "512Mi"
                  cpu: "500m"
                requests:
                  memory: "256Mi"
                  cpu: "250m"
              ports:
              - containerPort: 80
              command:
                - "sleep"
                - "604800"

---

apiVersion: v1
kind: Service
metadata:
    name: openreplay
    labels:
        app: openreplay
spec:
    type: NodePort
    selector:
        app: openreplay
    ports:
        - port: 80
          targetPort: 80
          nodePort: 30080

